export const tableHeaders = [
  "Trip ID",
  "Arrrival",
  "Departure",
  "Travel Month",
  "Destination",
  "Acc. Manager",
  "Booking Date",
  "Agent",
  "Lead pax",
  "Order Value (USD)",
  "Payment Value (USD)",
  "Transfer Price",
  "Trip Status",
  "Ops Spoc",
  "Booking Status",
  "Vouchers",
  "Action",
];

export const tableRows = [
  {
    tripId: 1,
    arrival: "arrival",
    departure: "departure",
    travelMonth: "travel month",
    destination: "destination",
    accManager: "acc manager",
    bookingDate: "booking date",
    agent: "agent",
    leadPax: "lead pax",
    orderValue: "order value",
    paymentValue: "payment value",
    transferPrice: "transfer price",
    tripStatus: "Travelled",
    opsSpoc: "ops spoc",
    bookingStatus: "done",
    vouchers: "vouchers",
    action: "action",
  },
  {
    tripId: 2,
    arrival: "arrival",
    departure: "departure",
    travelMonth: "travel month",
    destination: "destination",
    accManager: "acc manager",
    bookingDate: "booking date",
    agent: "agent",
    leadPax: "lead pax",
    orderValue: "order value",
    paymentValue: "payment value",
    transferPrice: "transfer price",
    tripStatus: "Confirmed",
    opsSpoc: "ops spoc",
    bookingStatus: "pending",
    vouchers: "vouchers",
    action: "action",
  },
  {
    tripId: 3,
    arrival: "arrival",
    departure: "departure",
    travelMonth: "travel month",
    destination: "destination",
    accManager: "acc manager",
    bookingDate: "booking date",
    agent: "agent",
    leadPax: "lead pax",
    orderValue: "order value",
    paymentValue: "payment value",
    transferPrice: "transfer price",
    tripStatus: "Confirmed",
    opsSpoc: "ops spoc",
    bookingStatus: "pending",
    vouchers: "vouchers",
    action: "action",
  },
  {
    tripId: 4,
    arrival: "arrival",
    departure: "departure",
    travelMonth: "travel month",
    destination: "destination",
    accManager: "acc manager",
    bookingDate: "booking date",
    agent: "agent",
    leadPax: "lead pax",
    orderValue: "order value",
    paymentValue: "payment value",
    transferPrice: "transfer price",
    tripStatus: "Cancelled",
    opsSpoc: "ops spoc",
    bookingStatus: "pending",
    vouchers: "vouchers",
    action: "action",
  },
  {
    tripId: 5,
    arrival: "arrival",
    departure: "departure",
    travelMonth: "travel month",
    destination: "destination",
    accManager: "acc manager",
    bookingDate: "booking date",
    agent: "agent",
    leadPax: "lead pax",
    orderValue: "order value",
    paymentValue: "payment value",
    transferPrice: "transfer price",
    tripStatus: "Travelled",
    opsSpoc: "ops spoc",
    bookingStatus: "done",
    vouchers: "vouchers",
    action: "action",
  },
  {
    tripId: 6,
    arrival: "arrival",
    departure: "departure",
    travelMonth: "travel month",
    destination: "destination",
    accManager: "acc manager",
    bookingDate: "booking date",
    agent: "agent",
    leadPax: "lead pax",
    orderValue: "order value",
    paymentValue: "payment value",
    transferPrice: "transfer price",
    tripStatus: "On Tour",
    opsSpoc: "ops spoc",
    bookingStatus: "done",
    vouchers: "vouchers",
    action: "action",
  },
];
